apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nikunjsharmade/api-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: '4001'
            - name: USER_SERVICE
              value: https://user-service:4002
