import type { Hotel } from "../data/hotel";
export const HOTELS: Hotel[] = [
  {
    id: 1,
    name: "Hilton Downtown",
    city: "Toronto",
    price: 180,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=1",
    description: "Luxury hotel in the heart of downtown.",
  },
  {
    id: 2,
    name: "Sea View Resort",
    city: "Miami",
    price: 220,
    rating: 4.7,
    image: "https://picsum.photos/400/300?random=2",
    description: "Beachfront resort with ocean views.",
  },
  {
    id: 3,
    name: "Mountain Lodge",
    city: "Denver",
    price: 150,
    rating: 4.5,
    image: "https://picsum.photos/400/300?random=3",
    description: "Quiet mountain retreat.",
  },
  {
    id: 4,
    name: "City Central Inn",
    city: "New York",
    price: 200,
    rating: 4.6,
    image: "https://picsum.photos/400/300?random=4",
    description: "Modern hotel near Times Square.",
  },
  {
    id: 5,
    name: "Sunrise Suites",
    city: "Vancouver",
    price: 175,
    rating: 4.4,
    image: "https://picsum.photos/400/300?random=5",
    description: "Comfortable stay with mountain views.",
  },
  {
    id: 6,
    name: "Royal Palace Hotel",
    city: "London",
    price: 280,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=6",
    description: "Elegant luxury hotel.",
  },
  {
    id: 7,
    name: "Skyline Residency",
    city: "Chicago",
    price: 195,
    rating: 4.5,
    image: "https://picsum.photos/400/300?random=7",
    description: "City skyline from every room.",
  },
  {
    id: 8,
    name: "Ocean Breeze Hotel",
    city: "Los Angeles",
    price: 240,
    rating: 4.7,
    image: "https://picsum.photos/400/300?random=8",
    description: "Relax near the beach.",
  },
  {
    id: 9,
    name: "Maple Stay",
    city: "Montreal",
    price: 165,
    rating: 4.3,
    image: "https://picsum.photos/400/300?random=9",
    description: "Cozy hotel in old town.",
  },
  {
    id: 10,
    name: "Desert Pearl",
    city: "Phoenix",
    price: 155,
    rating: 4.4,
    image: "https://picsum.photos/400/300?random=10",
    description: "Peaceful desert experience.",
  },
  {
    id: 11,
    name: "Golden Crown",
    city: "Dubai",
    price: 350,
    rating: 5.0,
    image: "https://picsum.photos/400/300?random=11",
    description: "Luxury experience with skyline views.",
  },
  {
    id: 12,
    name: "Riverfront Hotel",
    city: "Calgary",
    price: 170,
    rating: 4.5,
    image: "https://picsum.photos/400/300?random=12",
    description: "Beautiful riverside property.",
  },
  {
    id: 13,
    name: "Park Avenue Inn",
    city: "Boston",
    price: 210,
    rating: 4.6,
    image: "https://picsum.photos/400/300?random=13",
    description: "Business hotel near downtown.",
  },
  {
    id: 14,
    name: "Lakeside Resort",
    city: "Seattle",
    price: 225,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=14",
    description: "Scenic lakefront accommodation.",
  },
  {
    id: 15,
    name: "Blue Horizon",
    city: "San Diego",
    price: 215,
    rating: 4.7,
    image: "https://picsum.photos/400/300?random=15",
    description: "Luxury beachside hotel.",
  },
  {
    id: 16,
    name: "Harbor View",
    city: "San Francisco",
    price: 310,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=16",
    description: "Views of the Golden Gate.",
  },
  {
    id: 17,
    name: "Comfort Haven",
    city: "Ottawa",
    price: 160,
    rating: 4.4,
    image: "https://picsum.photos/400/300?random=17",
    description: "Family-friendly accommodation.",
  },
  {
    id: 18,
    name: "Elite Grand",
    city: "Paris",
    price: 330,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=18",
    description: "Luxury in the heart of Paris.",
  },
  {
    id: 19,
    name: "Snow Peak Lodge",
    city: "Banff",
    price: 260,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=19",
    description: "Perfect mountain getaway.",
  },
  {
    id: 20,
    name: "Emerald Hotel",
    city: "Dublin",
    price: 205,
    rating: 4.6,
    image: "https://picsum.photos/400/300?random=20",
    description: "Classic European comfort.",
  },
  {
    id: 21,
    name: "Palm Resort",
    city: "Cancun",
    price: 275,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=21",
    description: "All-inclusive beachfront resort.",
  },
  {
    id: 22,
    name: "Urban Loft",
    city: "Berlin",
    price: 190,
    rating: 4.5,
    image: "https://picsum.photos/400/300?random=22",
    description: "Stylish city accommodation.",
  },
  {
    id: 23,
    name: "Aurora Inn",
    city: "Reykjavik",
    price: 295,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=23",
    description: "Northern lights experience.",
  },
  {
    id: 24,
    name: "Imperial Stay",
    city: "Tokyo",
    price: 315,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=24",
    description: "Modern hotel with premium amenities.",
  },
  {
    id: 25,
    name: "Harbor Suites",
    city: "Sydney",
    price: 280,
    rating: 4.7,
    image: "https://picsum.photos/400/300?random=25",
    description: "Harbor-facing luxury suites.",
  },
  {
    id: 26,
    name: "Grand Heritage",
    city: "Rome",
    price: 255,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=26",
    description: "Historic charm with modern comfort.",
  },
  {
    id: 27,
    name: "Green Valley Resort",
    city: "Zurich",
    price: 290,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=27",
    description: "Nature-inspired luxury.",
  },
  {
    id: 28,
    name: "Crystal Bay",
    city: "Singapore",
    price: 300,
    rating: 4.8,
    image: "https://picsum.photos/400/300?random=28",
    description: "Premium stay in the city center.",
  },
  {
    id: 29,
    name: "Sunset Retreat",
    city: "Goa",
    price: 145,
    rating: 4.4,
    image: "https://picsum.photos/400/300?random=29",
    description: "Relaxing beach vacation.",
  },
  {
    id: 30,
    name: "Sky Palace",
    city: "Hong Kong",
    price: 320,
    rating: 4.9,
    image: "https://picsum.photos/400/300?random=30",
    description: "Luxury rooms with panoramic skyline views.",
  },
];
